version: '3.7'

volumes:
    postgres:
    pgadmin:

services:
  database:
    container_name: hubla_db
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
#     networks:
#       - hubla_net
#   nextron:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - database
#     networks:
#       - hubla_net
#     ports:
#     - "8080:8080"
# networks:
#   nextron_net:
#     driver: "bridge"
    
